### ISSUE TITLE
Add a higher cap to the interval calculator's history

### ISSUE THREAD

**Issue by abspayd** [abspayd/music-companion#16]
## TODO
- [x] Add a capacity of 5 items to the interval calculator's history
- [x] Change the styling of old answers
     - [x] All answers in one block
     - [x] old answers small and not bold

**Comment by abspayd** [comment]
Closing - no longer relevant with re-write.
